version: "3.8"
 
services:
  client:
    build: ./client
    volumes:
      - ./client:/app
      - ./uploads:/home/uploads
    ports:
      - 5000:5000
  server:
    build: ./server
    volumes:
      - ./server:/app
      - ./uploads:/home/uploads
    ports:
      - 5001:5001
volumes:
  uploads: